### ISSUE TITLE
Error: Undefined constant "CURLOPT_CONTENT_LENGTH"

### ISSUE THREAD

**Issue by TheR0cketMan** [GJSBRT/whmcs-discord-connection#1]
![image](https://user-images.githubusercontent.com/79772069/213297146-b1836afc-b4a0-4fb5-ac59-c692f4fb8091.png)

When I go to test it, I just get this error. I have no idea what it means, but thought I'd make you aware of it, just in case you wasn't aware of it.

I would ask how to fix it, but I noticed you mentioned you aren't going to offer support.

EDIT: I forgot to mention, this error appears after the Discord Oath screen, as soon as you click "Authorise".

**Comment by GJSBRT** [comment]
Hi, is your PHP up to date and do you have the curl extension enabled? 

I indeed cannot provide support as I dont have a WHMCS installation which I can test with.

**Comment by TheR0cketMan** [comment]
> Hi, is your PHP up to date and do you have the curl extension enabled?
> 
> I indeed cannot provide support as I dont have a WHMCS installation which I can test with.

Hi, it is. We recently upgraded from PHP 7.4 to PHP 8.1 as WHMCS 8.6 now officially supports 8.1, cURL is enabled as per WHMCS requirements.

If you have Discord yourself, I'm more than willing to let you use our newly installed private developer licensed WHMCS installation to test it on :)

**Comment by GJSBRT** [comment]
Hi, I unfortunately don't have the time to look into this. You could try removing the curl parameter.
